Add files via upload
This file, TFIDF_By_Genre.py, uses the TFIDFVectorizer to generate top TF-IDF terms by genre. This uses the MetroLyrics data set: MetroCombinedLyrics.csv.

A CSV returning the top 20 words for each genre, followed by their TF-IDF scores, is provided the output. The format is the same as the previous TF-IDF scripts I had developed.

Line 37 is used to set a sample size for testing on datasets smaller than the full dataset. Using test sets of 100-2000 items I was able to resolve all apparent bugs and "gotchas". However, once starting to scale up the following error presented itself:

ValueError: [E088] Text of length 2405112 exceeds maximum of 1000000. The v2.x parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.

Resolution of this error will be required before the script can be executed on the full data set.